create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null default 'Player',
  credits numeric(12,2) not null default 1000 check (credits >= 0 and credits <= 1000000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.game_history (
  id bigint generated by default as identity primary key,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  game_id text not null,
  session_id uuid,
  bet numeric(12,2) not null default 0,
  delta numeric(12,2) not null default 0,
  balance_after numeric(12,2) not null default 0,
  outcome text not null default 'played',
  action text not null default 'system',
  created_at timestamptz not null default now()
);

create table if not exists public.game_sessions (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null references public.profiles(id) on delete cascade,
  game_id text not null,
  status text not null default 'active' check (status in ('active', 'complete')),
  bet numeric(12,2) not null default 0,
  state jsonb not null default '{}'::jsonb,
  version integer not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.multiplayer_tables (
  id uuid primary key default gen_random_uuid(),
  game_id text not null check (game_id in ('blackjack', 'poker', 'dice')),
  host_profile_id uuid not null references public.profiles(id) on delete cascade,
  stake numeric(12,2) not null check (stake > 0 and stake <= 10000),
  max_players integer not null default 6 check (max_players between 2 and 6),
  status text not null default 'waiting' check (status in ('waiting', 'active', 'complete', 'cancelled')),
  visibility text not null default 'public' check (visibility in ('public', 'private')),
  invite_code text not null unique,
  turn_profile_id uuid references public.profiles(id) on delete set null,
  turn_deadline_at timestamptz,
  public_state jsonb not null default '{}'::jsonb,
  version integer not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.multiplayer_table_seats (
  table_id uuid not null references public.multiplayer_tables(id) on delete cascade,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  seat_index integer not null check (seat_index between 0 and 5),
  username text not null default 'Player',
  status text not null default 'seated' check (status in ('seated', 'ready', 'active', 'settled', 'left', 'abandoned')),
  settled_delta numeric(12,2) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (table_id, profile_id),
  unique (table_id, seat_index)
);

create table if not exists public.multiplayer_table_state (
  table_id uuid primary key references public.multiplayer_tables(id) on delete cascade,
  state jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.game_history add column if not exists session_id uuid;
alter table public.game_history add column if not exists multiplayer_table_id uuid;
alter table public.game_history add column if not exists balance_after numeric(12,2) not null default 0;
alter table public.game_history add column if not exists action text not null default 'system';
alter table public.profiles alter column credits type numeric(12,2) using credits::numeric(12,2);
alter table public.game_history alter column bet type numeric(12,2) using bet::numeric(12,2);
alter table public.game_history alter column delta type numeric(12,2) using delta::numeric(12,2);

do $$
begin
  if not exists (
    select 1
    from information_schema.table_constraints
    where constraint_schema = 'public'
      and table_name = 'game_history'
      and constraint_name = 'game_history_session_id_fkey'
  ) then
    alter table public.game_history
    add constraint game_history_session_id_fkey
    foreign key (session_id) references public.game_sessions(id) on delete set null;
  end if;
end;
$$;

do $$
begin
  if not exists (
    select 1
    from information_schema.table_constraints
    where constraint_schema = 'public'
      and table_name = 'game_history'
      and constraint_name = 'game_history_multiplayer_table_id_fkey'
  ) then
    alter table public.game_history
    add constraint game_history_multiplayer_table_id_fkey
    foreign key (multiplayer_table_id) references public.multiplayer_tables(id) on delete set null;
  end if;
end;
$$;

alter table public.profiles enable row level security;
alter table public.game_history enable row level security;
alter table public.game_sessions enable row level security;
alter table public.multiplayer_tables enable row level security;
alter table public.multiplayer_table_seats enable row level security;
alter table public.multiplayer_table_state enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
drop policy if exists "profiles_insert_own" on public.profiles;
drop policy if exists "profiles_update_own" on public.profiles;
drop policy if exists "history_select_own" on public.game_history;
drop policy if exists "history_insert_own" on public.game_history;
drop policy if exists "sessions_select_own" on public.game_sessions;
drop policy if exists "multiplayer_tables_select_lobby_or_seated" on public.multiplayer_tables;
drop policy if exists "multiplayer_seats_select_lobby_or_seated" on public.multiplayer_table_seats;
drop policy if exists "multiplayer_state_select_never" on public.multiplayer_table_state;

create or replace function public.is_multiplayer_table_member(p_table_id uuid)
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.multiplayer_table_seats seats
    where seats.table_id = p_table_id
      and seats.profile_id = (select auth.uid())
      and seats.status in ('seated', 'ready', 'active', 'settled')
  );
$$;

create or replace function public.is_multiplayer_table_public(p_table_id uuid)
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.multiplayer_tables tables
    where tables.id = p_table_id
      and tables.visibility = 'public'
  );
$$;

create policy "profiles_select_own"
on public.profiles for select
to authenticated
using ((select auth.uid()) = id);

create policy "history_select_own"
on public.game_history for select
to authenticated
using ((select auth.uid()) = profile_id);

create policy "multiplayer_tables_select_lobby_or_seated"
on public.multiplayer_tables for select
to authenticated
using (
  visibility = 'public'
  or public.is_multiplayer_table_member(id)
);

create policy "multiplayer_seats_select_lobby_or_seated"
on public.multiplayer_table_seats for select
to authenticated
using (
  public.is_multiplayer_table_public(table_id)
  or public.is_multiplayer_table_member(table_id)
);

grant usage on schema public to authenticated;
grant select on public.profiles to authenticated;
grant select on public.game_history to authenticated;
grant select on public.multiplayer_tables to authenticated;
grant select on public.multiplayer_table_seats to authenticated;

grant usage on schema public to service_role;
grant select, insert, update, delete on public.profiles to service_role;
grant select, insert, update, delete on public.game_history to service_role;
grant select, insert, update, delete on public.game_sessions to service_role;
grant select, insert, update, delete on public.multiplayer_tables to service_role;
grant select, insert, update, delete on public.multiplayer_table_seats to service_role;
grant select, insert, update, delete on public.multiplayer_table_state to service_role;
grant usage, select on all sequences in schema public to service_role;

revoke insert, update, delete on public.profiles from anon, authenticated;
revoke insert, update, delete on public.game_history from anon, authenticated;
revoke all on public.game_sessions from anon, authenticated;
revoke insert, update, delete on public.multiplayer_tables from anon, authenticated;
revoke insert, update, delete on public.multiplayer_table_seats from anon, authenticated;
revoke all on public.multiplayer_table_state from anon, authenticated;

do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    if not exists (
      select 1 from pg_publication_tables
      where pubname = 'supabase_realtime'
        and schemaname = 'public'
        and tablename = 'multiplayer_tables'
    ) then
      alter publication supabase_realtime add table public.multiplayer_tables;
    end if;

    if not exists (
      select 1 from pg_publication_tables
      where pubname = 'supabase_realtime'
        and schemaname = 'public'
        and tablename = 'multiplayer_table_seats'
    ) then
      alter publication supabase_realtime add table public.multiplayer_table_seats;
    end if;
  end if;
end;
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, username, credits)
  values (
    new.id,
    coalesce(nullif(new.raw_user_meta_data ->> 'username', ''), split_part(new.email, '@', 1), 'Player'),
    1000
  )
  on conflict on constraint profiles_pkey do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

create or replace function public.ensure_profile(p_profile_id uuid, p_username text default 'Player')
returns table(id uuid, username text, credits numeric)
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, username, credits)
  values (p_profile_id, coalesce(nullif(p_username, ''), 'Player'), 1000)
  on conflict on constraint profiles_pkey do nothing;

  return query
    select profiles.id, profiles.username, profiles.credits
    from public.profiles
    where profiles.id = p_profile_id;
end;
$$;

create or replace function public.create_game_session(
  p_profile_id uuid,
  p_game_id text,
  p_state jsonb,
  p_status text,
  p_bet numeric,
  p_delta numeric,
  p_outcome text,
  p_action text
)
returns table(session_id uuid, credits numeric, session_version integer)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_credits numeric(12,2);
  v_new_credits numeric(12,2);
  v_session_id uuid;
begin
  perform public.ensure_profile(p_profile_id, 'Player');

  select profiles.credits
  into v_credits
  from public.profiles
  where profiles.id = p_profile_id
  for update;

  v_new_credits := round(v_credits + p_delta, 2);

  if v_new_credits < 0 then
    raise exception 'insufficient_credits';
  end if;

  insert into public.game_sessions (profile_id, game_id, status, bet, state)
  values (p_profile_id, p_game_id, p_status, p_bet, p_state)
  returning game_sessions.id into v_session_id;

  update public.profiles
  set credits = v_new_credits,
      updated_at = now()
  where profiles.id = p_profile_id;

  insert into public.game_history (profile_id, session_id, game_id, bet, delta, balance_after, outcome, action)
  values (p_profile_id, v_session_id, p_game_id, p_bet, p_delta, v_new_credits, p_outcome, p_action);

  return query select v_session_id, v_new_credits, 1;
end;
$$;

create or replace function public.apply_game_step(
  p_profile_id uuid,
  p_session_id uuid,
  p_expected_version integer,
  p_game_id text,
  p_state jsonb,
  p_status text,
  p_bet numeric,
  p_delta numeric,
  p_outcome text,
  p_action text
)
returns table(credits numeric, session_version integer)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_credits numeric(12,2);
  v_new_credits numeric(12,2);
  v_next_version integer;
begin
  perform public.ensure_profile(p_profile_id, 'Player');

  select profiles.credits
  into v_credits
  from public.profiles
  where profiles.id = p_profile_id
  for update;

  v_new_credits := round(v_credits + p_delta, 2);

  if v_new_credits < 0 then
    raise exception 'insufficient_credits';
  end if;

  update public.game_sessions
  set state = p_state,
      status = p_status,
      bet = p_bet,
      version = game_sessions.version + 1,
      updated_at = now()
  where game_sessions.id = p_session_id
    and game_sessions.profile_id = p_profile_id
    and game_sessions.game_id = p_game_id
    and game_sessions.status = 'active'
    and game_sessions.version = p_expected_version
  returning game_sessions.version into v_next_version;

  if v_next_version is null then
    raise exception 'stale_or_closed_game_session';
  end if;

  update public.profiles
  set credits = v_new_credits,
      updated_at = now()
  where profiles.id = p_profile_id;

  if p_delta <> 0 or p_status <> 'active' then
    insert into public.game_history (profile_id, session_id, game_id, bet, delta, balance_after, outcome, action)
    values (p_profile_id, p_session_id, p_game_id, p_bet, p_delta, v_new_credits, p_outcome, p_action);
  end if;

  return query select v_new_credits, v_next_version;
end;
$$;

create or replace function public.apply_multiplayer_credit_entries(
  p_table_id uuid,
  p_game_id text,
  p_entries jsonb
)
returns table(profile_id uuid, credits numeric)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_entry jsonb;
  v_profile_id uuid;
  v_bet numeric(12,2);
  v_delta numeric(12,2);
  v_credits numeric(12,2);
  v_new_credits numeric(12,2);
  v_outcome text;
  v_action text;
begin
  for v_entry in select * from jsonb_array_elements(p_entries)
  loop
    v_profile_id := (v_entry ->> 'profileId')::uuid;
    v_bet := coalesce(nullif(v_entry ->> 'bet', '')::numeric, 0);
    v_delta := coalesce(nullif(v_entry ->> 'delta', '')::numeric, 0);
    v_outcome := coalesce(nullif(v_entry ->> 'outcome', ''), 'played');
    v_action := coalesce(nullif(v_entry ->> 'action', ''), 'multiplayer');

    perform public.ensure_profile(v_profile_id, 'Player');

    select profiles.credits
    into v_credits
    from public.profiles
    where profiles.id = v_profile_id
    for update;

    v_new_credits := round(v_credits + v_delta, 2);

    if v_new_credits < 0 then
      raise exception 'insufficient_credits';
    end if;

    update public.profiles
    set credits = v_new_credits,
        updated_at = now()
    where profiles.id = v_profile_id;

    insert into public.game_history (profile_id, multiplayer_table_id, game_id, bet, delta, balance_after, outcome, action)
    values (v_profile_id, p_table_id, p_game_id, v_bet, v_delta, v_new_credits, v_outcome, v_action);

    profile_id := v_profile_id;
    credits := v_new_credits;
    return next;
  end loop;
end;
$$;

create or replace function public.apply_multiplayer_credit_entries_versioned(
  p_table_id uuid,
  p_game_id text,
  p_entries jsonb,
  p_table_version integer
)
returns table(profile_id uuid, credits numeric, table_version integer)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_entry jsonb;
  v_profile_id uuid;
  v_bet numeric(12,2);
  v_delta numeric(12,2);
  v_credits numeric(12,2);
  v_new_credits numeric(12,2);
  v_outcome text;
  v_action text;
begin
  for v_entry in select * from jsonb_array_elements(p_entries)
  loop
    v_profile_id := (v_entry ->> 'profileId')::uuid;
    v_bet := coalesce(nullif(v_entry ->> 'bet', '')::numeric, 0);
    v_delta := coalesce(nullif(v_entry ->> 'delta', '')::numeric, 0);
    v_outcome := coalesce(nullif(v_entry ->> 'outcome', ''), 'played');
    v_action := coalesce(nullif(v_entry ->> 'action', ''), 'multiplayer');

    perform public.ensure_profile(v_profile_id, 'Player');

    select profiles.credits
    into v_credits
    from public.profiles
    where profiles.id = v_profile_id
    for update;

    v_new_credits := round(v_credits + v_delta, 2);

    if v_new_credits < 0 then
      raise exception 'insufficient_credits';
    end if;

    update public.profiles
    set credits = v_new_credits,
        updated_at = now()
    where profiles.id = v_profile_id;

    insert into public.game_history (profile_id, multiplayer_table_id, game_id, bet, delta, balance_after, outcome, action)
    values (v_profile_id, p_table_id, p_game_id, v_bet, v_delta, v_new_credits, v_outcome, v_action);

    profile_id := v_profile_id;
    credits := v_new_credits;
    table_version := p_table_version;
    return next;
  end loop;
end;
$$;

create or replace function public.start_multiplayer_table_round(
  p_table_id uuid,
  p_expected_version integer,
  p_game_id text,
  p_state jsonb,
  p_public_state jsonb,
  p_turn_profile_id uuid,
  p_turn_deadline_at timestamptz,
  p_status text,
  p_entries jsonb
)
returns table(profile_id uuid, credits numeric, table_version integer)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_table public.multiplayer_tables%rowtype;
  v_changed integer;
  v_next_version integer;
begin
  select tables.*
  into v_table
  from public.multiplayer_tables tables
  where tables.id = p_table_id
  for update;

  if v_table.id is null then
    raise exception 'multiplayer_table_not_found';
  end if;

  if v_table.status <> 'waiting' or v_table.version <> p_expected_version or v_table.game_id <> p_game_id then
    raise exception 'stale_multiplayer_table';
  end if;

  if p_status not in ('active', 'complete') then
    raise exception 'invalid_multiplayer_status';
  end if;

  update public.multiplayer_table_seats seats
  set status = 'active',
      updated_at = now()
  from (
    select (entry ->> 'profileId')::uuid as profile_id
    from jsonb_array_elements(p_entries) entry
  ) entries
  where seats.table_id = p_table_id
    and seats.profile_id = entries.profile_id
    and seats.status in ('seated', 'ready');

  get diagnostics v_changed = row_count;
  if v_changed <> jsonb_array_length(p_entries) then
    raise exception 'multiplayer_seats_changed';
  end if;

  insert into public.multiplayer_table_state (table_id, state, updated_at)
  values (p_table_id, p_state, now())
  on conflict (table_id) do update
  set state = excluded.state,
      updated_at = excluded.updated_at;

  v_next_version := v_table.version + 1;

  update public.multiplayer_tables tables
  set status = p_status,
      public_state = p_public_state,
      turn_profile_id = p_turn_profile_id,
      turn_deadline_at = p_turn_deadline_at,
      version = v_next_version,
      updated_at = now()
  where tables.id = p_table_id;

  return query
    select entries.profile_id, entries.credits, entries.table_version
    from public.apply_multiplayer_credit_entries_versioned(p_table_id, p_game_id, p_entries, v_next_version) entries;
end;
$$;

create or replace function public.apply_multiplayer_table_step(
  p_table_id uuid,
  p_expected_version integer,
  p_game_id text,
  p_state jsonb,
  p_public_state jsonb,
  p_turn_profile_id uuid,
  p_turn_deadline_at timestamptz,
  p_status text,
  p_entries jsonb
)
returns table(profile_id uuid, credits numeric, table_version integer)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_table public.multiplayer_tables%rowtype;
  v_changed integer;
  v_next_version integer;
  v_entry_count integer;
begin
  select tables.*
  into v_table
  from public.multiplayer_tables tables
  where tables.id = p_table_id
  for update;

  if v_table.id is null then
    raise exception 'multiplayer_table_not_found';
  end if;

  if v_table.status <> 'active' or v_table.version <> p_expected_version or v_table.game_id <> p_game_id then
    raise exception 'stale_multiplayer_step';
  end if;

  if p_status not in ('active', 'complete') then
    raise exception 'invalid_multiplayer_status';
  end if;

  v_entry_count := jsonb_array_length(p_entries);

  insert into public.multiplayer_table_state (table_id, state, updated_at)
  values (p_table_id, p_state, now())
  on conflict (table_id) do update
  set state = excluded.state,
      updated_at = excluded.updated_at;

  if v_entry_count > 0 then
    update public.multiplayer_table_seats seats
    set status = 'settled',
        settled_delta = entries.settled_delta,
        updated_at = now()
    from (
      select
        (entry ->> 'profileId')::uuid as profile_id,
        coalesce(nullif(entry ->> 'settledDelta', '')::numeric, 0) as settled_delta
      from jsonb_array_elements(p_entries) entry
    ) entries
    where seats.table_id = p_table_id
      and seats.profile_id = entries.profile_id
      and seats.status = 'active';

    get diagnostics v_changed = row_count;
    if v_changed <> v_entry_count then
      raise exception 'multiplayer_settlement_changed';
    end if;
  end if;

  v_next_version := v_table.version + 1;

  update public.multiplayer_tables tables
  set status = p_status,
      public_state = p_public_state,
      turn_profile_id = p_turn_profile_id,
      turn_deadline_at = p_turn_deadline_at,
      version = v_next_version,
      updated_at = now()
  where tables.id = p_table_id;

  if v_entry_count > 0 then
    return query
      select entries.profile_id, entries.credits, entries.table_version
      from public.apply_multiplayer_credit_entries_versioned(p_table_id, p_game_id, p_entries, v_next_version) entries;
  end if;
end;
$$;

revoke execute on function public.ensure_profile(uuid, text) from public, anon, authenticated;
revoke execute on function public.create_game_session(uuid, text, jsonb, text, numeric, numeric, text, text) from public, anon, authenticated;
revoke execute on function public.apply_game_step(uuid, uuid, integer, text, jsonb, text, numeric, numeric, text, text) from public, anon, authenticated;
revoke execute on function public.apply_multiplayer_credit_entries(uuid, text, jsonb) from public, anon, authenticated;
revoke execute on function public.apply_multiplayer_credit_entries_versioned(uuid, text, jsonb, integer) from public, anon, authenticated;
revoke execute on function public.start_multiplayer_table_round(uuid, integer, text, jsonb, jsonb, uuid, timestamptz, text, jsonb) from public, anon, authenticated;
revoke execute on function public.apply_multiplayer_table_step(uuid, integer, text, jsonb, jsonb, uuid, timestamptz, text, jsonb) from public, anon, authenticated;
revoke execute on function public.is_multiplayer_table_member(uuid) from public, anon;
revoke execute on function public.is_multiplayer_table_public(uuid) from public, anon;

grant execute on function public.ensure_profile(uuid, text) to service_role;
grant execute on function public.create_game_session(uuid, text, jsonb, text, numeric, numeric, text, text) to service_role;
grant execute on function public.apply_game_step(uuid, uuid, integer, text, jsonb, text, numeric, numeric, text, text) to service_role;
grant execute on function public.apply_multiplayer_credit_entries(uuid, text, jsonb) to service_role;
grant execute on function public.apply_multiplayer_credit_entries_versioned(uuid, text, jsonb, integer) to service_role;
grant execute on function public.start_multiplayer_table_round(uuid, integer, text, jsonb, jsonb, uuid, timestamptz, text, jsonb) to service_role;
grant execute on function public.apply_multiplayer_table_step(uuid, integer, text, jsonb, jsonb, uuid, timestamptz, text, jsonb) to service_role;
grant execute on function public.is_multiplayer_table_member(uuid) to authenticated;
grant execute on function public.is_multiplayer_table_public(uuid) to authenticated;
